### ISSUE TITLE
why embedding2pid list index out of range

### ISSUE THREAD

**Issue by GNEHUY** [Hannibal046/nanoColBERT#7]
When I run retrieve.py, I encounter an error with the line：
```
 top_relevant_doc_pids = [embedding2pid[x] for y in I for x in y]
```
Upon inspection, I found the error indexes retrieved. Why is this happening?

My debug：
```
total_embeddings.shape= torch.Size([596847651, 128])
len(embedding2pid)= 596847471

I:
[[406822639 117817889 368295592 ... 340840928  44116417  58849792]
 [ 47088131 301290898  47088044 ... 126308015 284803824 288093606]
 [ 47088131 442551456  47088044 ... 540478083 300737160 316488359]
 ...
 [150980019 102136117 410337895 ...  39484138 289150555 571997339]
 [404093947 376114314 404093855 ... 166449253  32960475 549894389]
 [421370365  89232576 399436776 ... 501989308 415117993 378354340]]

IndexError occurred. Details:
Current y: [406822639 117817889 368295592 ... 340840928  44116417  58849792]
Current x: 596867001

Traceback (most recent call last):
  File "retrieve.py", line 140, in <module>
    raise e
  File "retrieve.py", line 138, in <module>
    raise e
  File "retrieve.py", line 132, in <module>
    pid = embedding2pid[x]
IndexError: list index out of range
```

**Comment by Hannibal046** [comment]
Hi, could you please check the construction of faiss index? This is not expected, because it exceeds the max embedding number:
![image](https://github.com/Hannibal046/nanoColBERT/assets/38466901/f017d59a-28c9-40ab-9252-828cb28b252d)

**Comment by GNEHUY** [comment]
Yes, I know that the max embedding number has been exceeded. This is the result I discovered during my check. I modified the following code during the build index process because my faiss-gpu version is 1.7.0. It prompted that the input needs to be a numpy array, and I am building it on a 24GB RTX3090. Below is the code I modified in build_index.py.
```
    gpu_resource = faiss.StandardGpuResources()
    gpu_quantizer = faiss.index_cpu_to_gpu(gpu_resource, 0, quantizer)
    gpu_index = faiss.index_cpu_to_gpu(gpu_resource, 0, index)
    # faiss version:faiss-gpu=1.7.0, need numpy array
    embeddings_for_training = np.array(embeddings_for_training, dtype=np.float32)
    gpu_index.train(embeddings_for_training)

    ## add
    ## if OOM, try to split into small batches
    batch_size = 1000
    for file in tqdm(embedding_files,desc='loading from embedding files'):
        data = torch.load(file)
        data = np.array(data, dtype=np.float32)
        # Split data into batches
        for i in range(0, len(data), batch_size):
            batch_data = data[i:i+batch_size]
            gpu_index.add(batch_data)

        # Add the remaining data if it doesn't fill a complete batch
        if len(data) % batch_size != 0:
            remaining_data = data[(len(data) // batch_size) * batch_size:]
            gpu_index.add(remaining_data)

    cpu_index = faiss.index_gpu_to_cpu(gpu_index)
```

**Comment by Hannibal046** [comment]
so what is your indexed embedding number in total?

**Comment by GNEHUY** [comment]
The number of vectors in the Faiss index is: 596870942
```
faiss_index = faiss.read_index("embedding/colbert/ivfpq.faiss.index")
index_shape = faiss_index.ntotal
print(index_shape)
```
But all_token_embeddings.shape = [586847651, 128]
```
    # 2. sentence level reranking
    all_token_embeddings = []
    for file in embedding_files:
        print(f"loading {file}", flush=True)
        all_token_embeddings.append(torch.load(file))
    dummy_embeddings = torch.zeros((args.doc_max_len,DIM)) ## since we select each doc with doc_max_len
    all_token_embeddings.append(dummy_embeddings)
    all_token_embeddings = torch.cat(all_token_embeddings,dim=0)
    print("total_embeddings.shape=",all_token_embeddings.shape, flush=True)
```
As for the code snippet related to building the index, there seems to be a potential issue. The code is loading embeddings from files, splitting them into batches, and adding them to the index. Is it a problem with the following code? How should I fix it?
```
    batch_size = 1000
    for file in tqdm(embedding_files,desc='loading from embedding files'):
        data = torch.load(file)
        data = np.array(data, dtype=np.float32)
        # Split data into batches
        for i in range(0, len(data), batch_size):
            batch_data = data[i:i+batch_size]
            gpu_index.add(batch_data)

        # Add the remaining data if it doesn't fill a complete batch
        if len(data) % batch_size != 0:
            remaining_data = data[(len(data) // batch_size) * batch_size:]
            gpu_index.add(remaining_data)

    cpu_index = faiss.index_gpu_to_cpu(gpu_index)
```

**Comment by GNEHUY** [comment]
I found that it seems we don't need the following code, because adding it caused an increase in the number of vectors in the faiss_index. Is that correct?
```
# Add the remaining data if it doesn't fill a complete batch
if len(data) % batch_size != 0:
    remaining_data = data[(len(data) // batch_size) * batch_size:]
    gpu_index.add(remaining_data)
```

**Comment by Hannibal046** [comment]
```python
>>> l = range(10)
>>> batch_size = 3
>>> print([l[idx:idx+batch_size] for idx in range(0,len(l),batch_size)])
[range(0, 3), range(3, 6), range(6, 9), range(9, 10)]
```

**Comment by GNEHUY** [comment]
Thank you for your patient and timely response!  It's true, there was indeed an issue at this point.
